name: Deploy App Node.js con Docker



on:

 push:

  branches: [ main ]



jobs:

 deploy:

  runs-on: ubuntu-latest

  

  steps:

   - name: Checkout el código

    uses: actions/checkout@v4



   - name: Instalar Docker

    uses: docker/setup-buildx-action@v3



   - name: Construir imagen Docker

    run: docker build -t myapp:latest .



   - name: Correr contenedor Docker

    run: docker run -d -p 3000:3000 myapp:latest



Mensaje
Editor de texto